package com.hoteltv.manager;
import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.view.*;import android.widget.*;import java.io.*;import java.net.*;import org.json.*;import java.util.*;
public class MainActivity extends Activity{
 final String api="https://hoteltv-manager.mywire.org/api/v1"; LinearLayout root; TextView status;
 public void onCreate(Bundle b){super.onCreate(b); showWelcome();}
 TextView text(String s,int sp){TextView v=new TextView(this);v.setText(s);v.setTextColor(Color.WHITE);v.setTextSize(sp);v.setPadding(16,12,16,12);return v;}
 Button button(String s){Button b=new Button(this);b.setText(s);b.setMinHeight(72);b.setOnFocusChangeListener((v,f)->v.setScaleX(f?1.04f:1f));return b;}
 void base(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setGravity(Gravity.CENTER);root.setPadding(80,40,80,40);root.setBackgroundColor(Color.rgb(7,17,31));setContentView(root);root.addView(text("HotelTV",34));}
 void showWelcome(){base();root.addView(text("Choose how to set up this television",22));Button a=button("Activate with Hotel Manager");a.setOnClickListener(v->activate());root.addView(a,new LinearLayout.LayoutParams(600,-2));Button d=button("Sign in with Xtream Codes");d.setOnClickListener(v->direct());root.addView(d,new LinearLayout.LayoutParams(600,-2));}
 void direct(){base();EditText name=input("Playlist name"),server=input("Server URL"),user=input("Username"),pass=input("Password");pass.setInputType(129);root.addView(name);root.addView(server);root.addView(user);root.addView(pass);status=text("",16);root.addView(status);Button login=button("Sign in");login.setOnClickListener(v->new Thread(()->xtream(name.getText().toString(),server.getText().toString(),user.getText().toString(),pass.getText().toString())).start());root.addView(login);}
 EditText input(String hint){EditText e=new EditText(this);e.setHint(hint);e.setTextColor(Color.WHITE);e.setHintTextColor(Color.LTGRAY);e.setSingleLine(true);e.setMinWidth(700);return e;}
 void xtream(String n,String s,String u,String p){try{String base=s.replaceAll("/+$","");JSONObject j=get(base+"/player_api.php?username="+URLEncoder.encode(u,"UTF-8")+"&password="+URLEncoder.encode(p,"UTF-8"));boolean ok=j.optJSONObject("user_info")!=null&&j.getJSONObject("user_info").optInt("auth",0)==1;if(!ok)throw new Exception("Account rejected");getPreferences(0).edit().putString("playlist_name",n).putString("server",base).putString("username",u).putString("password",p).apply();runOnUiThread(()->{status.setText("Login successful. Playlist saved.");});}catch(Exception e){runOnUiThread(()->status.setText("Login failed: "+e.getMessage()));}}
 void activate(){base();status=text("Requesting activation code…",22);root.addView(status);new Thread(()->{try{String id=Settings.Secure.getString(getContentResolver(),Settings.Secure.ANDROID_ID);JSONObject body=new JSONObject();body.put("deviceUuid",id);body.put("deviceModel",Build.MODEL);body.put("androidVersion",Build.VERSION.RELEASE);body.put("appVersion","0.1.0-alpha1");JSONObject r=post(api+"/activation-code.php",body);runOnUiThread(()->status.setText("Activation code\n\n"+r.optString("activationCode")+"\n\nEnter this code in HotelTV Manager"));}catch(Exception e){runOnUiThread(()->status.setText("Activation failed: "+e.getMessage()));}}).start();}
 JSONObject get(String url)throws Exception{return request(url,null);}
 JSONObject post(String url,JSONObject b)throws Exception{return request(url,b);}
 JSONObject request(String u,JSONObject b)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setConnectTimeout(12000);c.setReadTimeout(12000);if(b!=null){c.setRequestMethod("POST");c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json");try(OutputStream o=c.getOutputStream()){o.write(b.toString().getBytes("UTF-8"));}}InputStream in=(c.getResponseCode()<400?c.getInputStream():c.getErrorStream());BufferedReader r=new BufferedReader(new InputStreamReader(in));StringBuilder x=new StringBuilder();String l;while((l=r.readLine())!=null)x.append(l);return new JSONObject(x.toString());}
}
