<?php
declare(strict_types=1);
require dirname(__DIR__).'/hoteltv/bootstrap/app.php';
hoteltv_require_admin();
$errors=array();
$properties=$pdo->query('SELECT * FROM properties ORDER BY name')->fetchAll();
if($_SERVER['REQUEST_METHOD']==='POST'){
 hoteltv_verify_csrf();$action=(string)$_POST['action'];$now=gmdate('c');
 if($action==='account_save'){
  $id=(int)$_POST['id'];$property=(int)$_POST['property_id'];$name=trim($_POST['name']);$server=rtrim(trim($_POST['server_url']),'/');$username=trim($_POST['username']);$password=(string)$_POST['password'];
  if($name===''||$server===''||$username==='')$errors[]='Name, server URL and username are required.';
  if(!$errors){if($id){$row=$pdo->prepare('SELECT * FROM iptv_accounts WHERE id=?');$row->execute(array($id));$old=$row->fetch();$u=$username!==''?hoteltv_encrypt($username,$config):$old['username_encrypted'];$p=$password!==''?hoteltv_encrypt($password,$config):$old['password_encrypted'];$pdo->prepare('UPDATE iptv_accounts SET property_id=?,name=?,server_url=?,username_encrypted=?,password_encrypted=?,active=?,updated_at=? WHERE id=?')->execute(array($property,$name,$server,$u,$p,isset($_POST['active'])?1:0,$now,$id));hoteltv_audit($pdo,'update','iptv_account',$id);}else{$pdo->prepare('INSERT INTO iptv_accounts(property_id,name,server_url,username_encrypted,password_encrypted,active,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)')->execute(array($property,$name,$server,hoteltv_encrypt($username,$config),hoteltv_encrypt($password,$config),1,$now,$now));$id=(int)$pdo->lastInsertId();hoteltv_audit($pdo,'create','iptv_account',$id);}hoteltv_flash('success','IPTV account saved.');header('Location:/iptv.php');exit;}
 }
 if($action==='account_delete'){$id=(int)$_POST['id'];$st=$pdo->prepare('SELECT COUNT(*) FROM playlist_profiles WHERE iptv_account_id=?');$st->execute(array($id));if((int)$st->fetchColumn()>0)hoteltv_flash('error','Remove or reassign playlist profiles using this account first.');else{$pdo->prepare('DELETE FROM iptv_accounts WHERE id=?')->execute(array($id));hoteltv_audit($pdo,'delete','iptv_account',$id);hoteltv_flash('success','IPTV account removed.');}header('Location:/iptv.php');exit;}
 if($action==='profile_save'){$id=(int)$_POST['id'];$property=(int)$_POST['property_id'];$account=(int)$_POST['iptv_account_id'];$name=trim($_POST['name']);if($name==='')$errors[]='Profile name is required.';if(!$errors){$settings=json_encode(array('guest_mode'=>true,'external_player'=>false));if($id){$pdo->prepare('UPDATE playlist_profiles SET property_id=?,iptv_account_id=?,name=?,settings_json=?,updated_at=? WHERE id=?')->execute(array($property,$account?:null,$name,$settings,$now,$id));}else{$pdo->prepare('INSERT INTO playlist_profiles(property_id,iptv_account_id,name,settings_json,created_at,updated_at) VALUES(?,?,?,?,?,?)')->execute(array($property,$account?:null,$name,$settings,$now,$now));$id=(int)$pdo->lastInsertId();}hoteltv_audit($pdo,'save','playlist_profile',$id);hoteltv_flash('success','Playlist profile saved.');header('Location:/iptv.php');exit;}}
 if($action==='profile_delete'){$id=(int)$_POST['id'];$pdo->prepare('DELETE FROM playlist_profiles WHERE id=?')->execute(array($id));hoteltv_audit($pdo,'delete','playlist_profile',$id);hoteltv_flash('success','Playlist profile removed.');header('Location:/iptv.php');exit;}
}
$editAccount=null;$editProfile=null;
if(isset($_GET['edit_account'])){$st=$pdo->prepare('SELECT * FROM iptv_accounts WHERE id=?');$st->execute(array((int)$_GET['edit_account']));$editAccount=$st->fetch();}
if(isset($_GET['edit_profile'])){$st=$pdo->prepare('SELECT * FROM playlist_profiles WHERE id=?');$st->execute(array((int)$_GET['edit_profile']));$editProfile=$st->fetch();}
$accounts=$pdo->query('SELECT i.*,p.name property_name,(SELECT COUNT(*) FROM playlist_profiles pp WHERE pp.iptv_account_id=i.id) profile_count FROM iptv_accounts i JOIN properties p ON p.id=i.property_id ORDER BY i.name')->fetchAll();
$profiles=$pdo->query('SELECT pp.*,p.name property_name,i.name account_name FROM playlist_profiles pp JOIN properties p ON p.id=pp.property_id LEFT JOIN iptv_accounts i ON i.id=pp.iptv_account_id ORDER BY pp.name')->fetchAll();
hoteltv_admin_header('IPTV','iptv');foreach($errors as $e)echo '<div class="alert error">'.h($e).'</div>';
?>
<div class="two-column"><section>
<div class="card"><div class="section-head"><div><h2>Xtream Codes accounts</h2><p>Credentials are encrypted outside the public web root.</p></div></div><?php if(!$accounts):?><div class="empty"><strong>No IPTV accounts yet</strong><p>Add the first licensed Xtream Codes v2 account.</p></div><?php else:?><div class="table-wrap"><table><thead><tr><th>Account</th><th>Property</th><th>Server</th><th>Status</th><th>Profiles</th><th>Actions</th></tr></thead><tbody><?php foreach($accounts as $a):?><tr><td><strong><?=h($a['name'])?></strong></td><td><?=h($a['property_name'])?></td><td><small><?=h($a['server_url'])?></small></td><td><span class="status status-<?=$a['active']?'active':'inactive'?>"><?=$a['active']?'Active':'Inactive'?></span></td><td><?=$a['profile_count']?></td><td><div class="actions-cell"><a class="button secondary small" href="?edit_account=<?=$a['id']?>#account-form">Edit</a><form method="post" class="inline-form"><input type="hidden" name="csrf_token" value="<?=h(hoteltv_csrf_token())?>"><input type="hidden" name="action" value="account_delete"><input type="hidden" name="id" value="<?=$a['id']?>"><button class="button danger small" data-confirm="Remove this IPTV account?">Remove</button></form></div></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></div>
<div class="card"><div class="section-head"><div><h2>Playlist profiles</h2><p>Reusable channel and playback settings for rooms and devices.</p></div></div><?php if(!$profiles):?><div class="empty">No playlist profiles yet.</div><?php else:?><div class="table-wrap"><table><thead><tr><th>Profile</th><th>Property</th><th>Account</th><th>Actions</th></tr></thead><tbody><?php foreach($profiles as $p):?><tr><td><strong><?=h($p['name'])?></strong></td><td><?=h($p['property_name'])?></td><td><?=h($p['account_name']?:'Unassigned')?></td><td><div class="actions-cell"><a class="button secondary small" href="?edit_profile=<?=$p['id']?>#profile-form">Edit</a><form method="post" class="inline-form"><input type="hidden" name="csrf_token" value="<?=h(hoteltv_csrf_token())?>"><input type="hidden" name="action" value="profile_delete"><input type="hidden" name="id" value="<?=$p['id']?>"><button class="button danger small" data-confirm="Remove this playlist profile?">Remove</button></form></div></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></div>
</section><aside>
<div class="card form-card" id="account-form"><h2><?=$editAccount?'Edit IPTV account':'Add IPTV account'?></h2><form method="post"><input type="hidden" name="csrf_token" value="<?=h(hoteltv_csrf_token())?>"><input type="hidden" name="action" value="account_save"><input type="hidden" name="id" value="<?=h($editAccount?$editAccount['id']:0)?>"><div class="field"><label>Property</label><select name="property_id"><?php foreach($properties as $p):?><option value="<?=$p['id']?>" <?=$editAccount&&$editAccount['property_id']==$p['id']?'selected':''?>><?=h($p['name'])?></option><?php endforeach;?></select></div><div class="field"><label>Account name</label><input name="name" value="<?=h($editAccount?$editAccount['name']:'')?>" required></div><div class="field"><label>Server URL</label><input type="url" name="server_url" value="<?=h($editAccount?$editAccount['server_url']:'')?>" placeholder="https://provider.example:443" required></div><div class="field"><label>Username</label><input name="username" value="<?=h($editAccount?hoteltv_decrypt($editAccount['username_encrypted'],$config):'')?>" required></div><div class="field"><label>Password <?=$editAccount?'<small>(leave blank to keep)</small>':''?></label><input type="password" name="password" <?=$editAccount?'':'required'?>></div><?php if($editAccount):?><div class="field"><label><input style="width:auto" type="checkbox" name="active" <?=$editAccount['active']?'checked':''?>> Account active</label></div><?php endif;?><div class="button-row"><button class="button primary">Save account</button><?php if($editAccount):?><a class="button secondary" href="/iptv.php">Cancel</a><?php endif;?></div></form></div>
<div class="card form-card" id="profile-form"><h2><?=$editProfile?'Edit profile':'Add playlist profile'?></h2><form method="post"><input type="hidden" name="csrf_token" value="<?=h(hoteltv_csrf_token())?>"><input type="hidden" name="action" value="profile_save"><input type="hidden" name="id" value="<?=h($editProfile?$editProfile['id']:0)?>"><div class="field"><label>Property</label><select name="property_id"><?php foreach($properties as $p):?><option value="<?=$p['id']?>" <?=$editProfile&&$editProfile['property_id']==$p['id']?'selected':''?>><?=h($p['name'])?></option><?php endforeach;?></select></div><div class="field"><label>IPTV account</label><select name="iptv_account_id"><option value="0">Unassigned</option><?php foreach($accounts as $a):?><option value="<?=$a['id']?>" <?=$editProfile&&$editProfile['iptv_account_id']==$a['id']?'selected':''?>><?=h($a['name'])?></option><?php endforeach;?></select></div><div class="field"><label>Profile name</label><input name="name" value="<?=h($editProfile?$editProfile['name']:'Standard Rooms')?>" required></div><div class="button-row"><button class="button primary">Save profile</button><?php if($editProfile):?><a class="button secondary" href="/iptv.php">Cancel</a><?php endif;?></div></form></div>
</aside></div><?php hoteltv_admin_footer(); ?>
