<?php
declare(strict_types=1);
require dirname(__DIR__) . '/hoteltv/bootstrap/app.php';
hoteltv_require_admin();
$errors = array();
$properties = $pdo->query('SELECT * FROM properties ORDER BY name')->fetchAll();
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    hoteltv_verify_csrf();
    $action = isset($_POST['action']) ? (string)$_POST['action'] : '';
    $now = gmdate('c');
    if ($action === 'floor_save') {
        $id=(int)(isset($_POST['id'])?$_POST['id']:0); $property=(int)$_POST['property_id']; $name=trim($_POST['floor_name']);
        if($name==='')$errors[]='Floor name is required.';
        if(!$errors){if($id){$pdo->prepare('UPDATE floors SET property_id=?,name=?,updated_at=? WHERE id=?')->execute(array($property,$name,$now,$id));hoteltv_audit($pdo,'update','floor',$id);}else{$pdo->prepare('INSERT INTO floors(property_id,name,sort_order,created_at,updated_at) VALUES(?,?,?,?,?)')->execute(array($property,$name,0,$now,$now));$id=(int)$pdo->lastInsertId();hoteltv_audit($pdo,'create','floor',$id);}hoteltv_flash('success','Floor saved.');header('Location:/rooms.php');exit;}
    }
    if ($action === 'floor_delete') {
        $id=(int)$_POST['id'];$st=$pdo->prepare('SELECT COUNT(*) FROM rooms WHERE floor_id=?');$st->execute(array($id));
        if((int)$st->fetchColumn()>0)hoteltv_flash('error','Move or remove the rooms on this floor first.');else{$pdo->prepare('DELETE FROM floors WHERE id=?')->execute(array($id));hoteltv_audit($pdo,'delete','floor',$id);hoteltv_flash('success','Floor removed.');}header('Location:/rooms.php');exit;
    }
    if ($action === 'room_save') {
        $id=(int)(isset($_POST['id'])?$_POST['id']:0);$property=(int)$_POST['property_id'];$floor=(int)$_POST['floor_id'];$number=trim($_POST['room_number']);$display=trim($_POST['display_name']);
        if($number==='')$errors[]='Room number is required.';
        if(!$errors){try{if($id){$pdo->prepare('UPDATE rooms SET property_id=?,floor_id=?,room_number=?,display_name=?,updated_at=? WHERE id=?')->execute(array($property,$floor?:null,$number,$display,$now,$id));hoteltv_audit($pdo,'update','room',$id);}else{$pdo->prepare('INSERT INTO rooms(property_id,floor_id,room_number,display_name,created_at,updated_at) VALUES(?,?,?,?,?,?)')->execute(array($property,$floor?:null,$number,$display,$now,$now));$id=(int)$pdo->lastInsertId();hoteltv_audit($pdo,'create','room',$id);}hoteltv_flash('success','Room saved.');header('Location:/rooms.php');exit;}catch(Throwable $e){$errors[]='That room number already exists for this property.';}}
    }
    if ($action === 'room_delete') {
        $id=(int)$_POST['id'];$st=$pdo->prepare('SELECT COUNT(*) FROM devices WHERE room_id=?');$st->execute(array($id));
        if((int)$st->fetchColumn()>0)hoteltv_flash('error','Unassign or remove the devices in this room first.');else{$pdo->prepare('DELETE FROM rooms WHERE id=?')->execute(array($id));hoteltv_audit($pdo,'delete','room',$id);hoteltv_flash('success','Room removed.');}header('Location:/rooms.php');exit;
    }
    if ($action === 'bulk') {
        $property=(int)$_POST['property_id'];$floor=(int)$_POST['floor_id'];$start=(int)$_POST['start_number'];$end=(int)$_POST['end_number'];
        if($start<1||$end<$start||($end-$start)>500)$errors[]='Enter a valid range of no more than 501 rooms.';else{$st=$pdo->prepare('INSERT INTO rooms(property_id,floor_id,room_number,display_name,created_at,updated_at) VALUES(?,?,?,?,?,?)');$added=0;for($i=$start;$i<=$end;$i++){try{$st->execute(array($property,$floor?:null,(string)$i,'Room '.$i,$now,$now));$added++;}catch(Throwable $e){}}hoteltv_audit($pdo,'bulk_create','room',0,array('added'=>$added));hoteltv_flash('success',$added.' rooms created.');header('Location:/rooms.php');exit;}
    }
}
$editFloor=null;$editRoom=null;
if(isset($_GET['edit_floor'])){$st=$pdo->prepare('SELECT * FROM floors WHERE id=?');$st->execute(array((int)$_GET['edit_floor']));$editFloor=$st->fetch();}
if(isset($_GET['edit_room'])){$st=$pdo->prepare('SELECT * FROM rooms WHERE id=?');$st->execute(array((int)$_GET['edit_room']));$editRoom=$st->fetch();}
$floors=$pdo->query('SELECT f.*,p.name property_name,(SELECT COUNT(*) FROM rooms r WHERE r.floor_id=f.id) room_count FROM floors f JOIN properties p ON p.id=f.property_id ORDER BY p.name,f.sort_order,f.name')->fetchAll();
$rooms=$pdo->query('SELECT r.*,p.name property_name,f.name floor_name,(SELECT COUNT(*) FROM devices d WHERE d.room_id=r.id) device_count FROM rooms r JOIN properties p ON p.id=r.property_id LEFT JOIN floors f ON f.id=r.floor_id ORDER BY p.name,f.sort_order,r.room_number')->fetchAll();
hoteltv_admin_header('Rooms & Floors','rooms');foreach($errors as $e)echo '<div class="alert error">'.h($e).'</div>';
?>
<div class="toolbar"><div><strong><?=count($rooms)?> rooms across <?=count($floors)?> floors</strong><div class="help">Create, edit and safely remove room inventory.</div></div></div>
<div class="dashboard-grid"><section>
<div class="card"><div class="section-head"><div><h2>Floors</h2><p>Organization within each property.</p></div></div><?php if(!$floors):?><div class="empty">No floors created yet.</div><?php else:?><div class="table-wrap"><table><thead><tr><th>Floor</th><th>Property</th><th>Rooms</th><th>Actions</th></tr></thead><tbody><?php foreach($floors as $f):?><tr><td><strong><?=h($f['name'])?></strong></td><td><?=h($f['property_name'])?></td><td><?=$f['room_count']?></td><td><div class="actions-cell"><a class="button secondary small" href="?edit_floor=<?=$f['id']?>#floor-form">Edit</a><form method="post" class="inline-form"><input type="hidden" name="csrf_token" value="<?=h(hoteltv_csrf_token())?>"><input type="hidden" name="action" value="floor_delete"><input type="hidden" name="id" value="<?=$f['id']?>"><button class="button danger small" data-confirm="Remove this floor? It must be empty first.">Remove</button></form></div></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></div>
<div class="card"><div class="section-head"><div><h2>Rooms</h2><p>Guest rooms and assigned televisions.</p></div></div><?php if(!$rooms):?><div class="empty">Create your first room using the form.</div><?php else:?><div class="table-wrap"><table><thead><tr><th>Room</th><th>Property</th><th>Floor</th><th>TVs</th><th>Actions</th></tr></thead><tbody><?php foreach($rooms as $r):?><tr><td><strong><?=h($r['display_name']?:'Room '.$r['room_number'])?></strong><small>#<?=h($r['room_number'])?></small></td><td><?=h($r['property_name'])?></td><td><?=h($r['floor_name']?:'Unassigned')?></td><td><?=$r['device_count']?></td><td><div class="actions-cell"><a class="button secondary small" href="?edit_room=<?=$r['id']?>#room-form">Edit</a><form method="post" class="inline-form"><input type="hidden" name="csrf_token" value="<?=h(hoteltv_csrf_token())?>"><input type="hidden" name="action" value="room_delete"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="button danger small" data-confirm="Remove room <?=h($r['room_number'])?>? It must have no assigned devices.">Remove</button></form></div></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></div>
</section><aside>
<section class="card form-card" id="floor-form"><h2><?=$editFloor?'Edit floor':'Add floor'?></h2><form method="post"><input type="hidden" name="csrf_token" value="<?=h(hoteltv_csrf_token())?>"><input type="hidden" name="action" value="floor_save"><input type="hidden" name="id" value="<?=h($editFloor?$editFloor['id']:0)?>"><div class="field"><label>Property</label><select name="property_id"><?php foreach($properties as $p):?><option value="<?=$p['id']?>" <?=$editFloor&&$editFloor['property_id']==$p['id']?'selected':''?>><?=h($p['name'])?></option><?php endforeach;?></select></div><div class="field"><label>Floor name</label><input name="floor_name" value="<?=h($editFloor?$editFloor['name']:'')?>" placeholder="Floor 2" required></div><div class="button-row"><button class="button primary">Save floor</button><?php if($editFloor):?><a class="button secondary" href="/rooms.php">Cancel</a><?php endif;?></div></form></section>
<section class="card form-card" id="room-form"><h2><?=$editRoom?'Edit room':'Add one room'?></h2><form method="post"><input type="hidden" name="csrf_token" value="<?=h(hoteltv_csrf_token())?>"><input type="hidden" name="action" value="room_save"><input type="hidden" name="id" value="<?=h($editRoom?$editRoom['id']:0)?>"><div class="field"><label>Property</label><select name="property_id"><?php foreach($properties as $p):?><option value="<?=$p['id']?>" <?=$editRoom&&$editRoom['property_id']==$p['id']?'selected':''?>><?=h($p['name'])?></option><?php endforeach;?></select></div><div class="field"><label>Floor</label><select name="floor_id"><option value="0">No floor</option><?php foreach($floors as $f):?><option value="<?=$f['id']?>" <?=$editRoom&&$editRoom['floor_id']==$f['id']?'selected':''?>><?=h($f['property_name'].' — '.$f['name'])?></option><?php endforeach;?></select></div><div class="field"><label>Room number</label><input name="room_number" value="<?=h($editRoom?$editRoom['room_number']:'')?>" required></div><div class="field"><label>Display name</label><input name="display_name" value="<?=h($editRoom?$editRoom['display_name']:'')?>" placeholder="Optional"></div><div class="button-row"><button class="button primary">Save room</button><?php if($editRoom):?><a class="button secondary" href="/rooms.php">Cancel</a><?php endif;?></div></form></section>
<section class="card form-card"><h2>Bulk-create rooms</h2><form method="post"><input type="hidden" name="csrf_token" value="<?=h(hoteltv_csrf_token())?>"><input type="hidden" name="action" value="bulk"><div class="field"><label>Property</label><select name="property_id"><?php foreach($properties as $p):?><option value="<?=$p['id']?>"><?=h($p['name'])?></option><?php endforeach;?></select></div><div class="field"><label>Floor</label><select name="floor_id"><option value="0">No floor</option><?php foreach($floors as $f):?><option value="<?=$f['id']?>"><?=h($f['property_name'].' — '.$f['name'])?></option><?php endforeach;?></select></div><div class="split-fields"><div class="field"><label>Start</label><input type="number" name="start_number" value="101"></div><div class="field"><label>End</label><input type="number" name="end_number" value="120"></div></div><button class="button">Create range</button></form></section>
</aside></div><?php hoteltv_admin_footer(); ?>
